set_property DONT_TOUCH TRUE [get_cells -hierarchical clkout1_buf_uplus]
set_property CLOCK_DELAY_GROUP group_bufgce [get_nets -of [get_pins -hierarchical clkout1_buf_uplus/O]]
set_property USER_CLOCK_ROOT X4Y6 [get_nets -of [get_pins -hierarchical clkout1_buf_uplus/O]]
set_property CLOCK_DELAY_GROUP group_bufgce [get_nets -of [get_pins -hierarchical clkout1_buf/O]]
set_property USER_CLOCK_ROOT X4Y6 [get_nets -of [get_pins -hierarchical clkout1_buf/O]]